/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 08/10/2024 17:37:23
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            48000000
#define MX_HSE_VALUE                            8000000
#define MX_AHBFreq_Value                        12000000
#define MX_APBFreq_Value                        12000000
#define MX_HCLKFreq_Value                       12000000
#define MX_CortexFreq_Value                     12000000
#define MX_SYSCLKFreq_VALUE                     12000000
#define MX_ADCFreq_Value                        12000000
#define MX_APBTimFreq_Value                     12000000
#define MX_I2C1Freq_Value                       12000000
#define MX_I2S1Freq_Value                       12000000
#define MX_FCLKCortexFreq_Value                 12000000
#define MX_RTCFreq_Value                        32000
#define MX_PWRFreq_Value                        12000000
#define MX_MCO1PinFreq_Value                    12000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_USART1Freq_Value                     12000000
#define MX_WatchDogFreq_Value                   32000

/*-------------------------------- CORTEX_M0+ --------------------------------*/

#define MX_CORTEX_M0+                           1

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

#endif  /* __MX_DEVICE_H */

